# Generated by Django 4.2.14 on 2024-07-26 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_type', models.CharField(choices=[('COW', 'Cow'), ('Sheep', 'Sheep'), ('Pig', 'Pig')], max_length=10, verbose_name='animal type')),
                ('breed', models.CharField(blank=True, max_length=10, verbose_name='breed')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('tag_number', models.CharField(blank=True, max_length=50, verbose_name='tag number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='gender')),
                ('acquisistion_date', models.DateField(blank=True, null=True, verbose_name='acquisition date')),
                ('acquisistion_method', models.CharField(choices=[('Born', 'Born'), ('Purchased', 'Purchased')], max_length=10, verbose_name='acquisition method')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Deceased', 'Deceased')], max_length=10, verbose_name='status')),
                ('current_weight', models.FloatField(blank=True, max_length=10, verbose_name='weight')),
                ('current_age', models.IntegerField(blank=True, max_length=5, verbose_name='age')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/profile_pictures/', verbose_name='profile picture')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
