# Generated by Django 4.2.14 on 2024-07-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='current_age',
            field=models.IntegerField(blank=True, verbose_name='age'),
        ),
    ]
